### GENERAL SETTINGS ###

# Site settings
title: FIL MACKAY
description: "Blog on high technology trading, data analytics, functional programming and unintended consequences."
analytics: UA-31692581-2
baseurl: "" #important: start with /
url: "http://filmackay.com"

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/filmackay
  - title: twitter
    url: https://twitter.com/filmackay

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - London, UK
email: fil@vergo.co
tel: +44 7849 211354

# Members information. Shown on About page.
members:
  - name: Fil Mackay
    position: Software Architect
    text: This is not actually me.
    img: team01.jpg
    social:
      - title: twitter
        url: http://twitter.com/handle

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Data awesome."
